/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: wallon (https://sketchfab.com/realwallon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/audi-r8-e17e438f076f4427a58d93aa779edaed
Title: Audi R8
*/


import { Html, useGLTF } from '@react-three/drei';
function Model(props) {
  const { nodes, materials } = useGLTF('/model/audi.glb');
  return (
    <group {...props} dispose={null}>
      <group scale={0.00075}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003_rim_0.geometry}
          material={materials.material}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_tire_0.geometry}
          material={materials.tire}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rear_wheels007_wheel_0.geometry}
          material={materials.wheel}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rear_wheels008_calipers_0.geometry}
          material={materials.calipers}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rear_wheels009_wheel_0.geometry}
          material={materials.wheel}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004_rim_0.geometry}
          material={materials.material}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_tire_0.geometry}
          material={materials.tire}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rear_wheels010_calipers_0.geometry}
          material={materials.calipers}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back_tail_light001_chrome_0.geometry}
          material={materials.chrome}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back_tail_light004_chrome_0.geometry}
          material={materials.chrome}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back_tail_light005_white_lights_0.geometry}
          material={materials.white_lights}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back_tail_light007_chrome_0.geometry}
          material={materials.chrome}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back_tail_light008_red_lights_0.geometry}
          material={materials.red_lights}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back_tail_light009_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back_tail_light010_chrome_0.geometry}
          material={materials.chrome}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back_tail_light011_glass_0.geometry}
          material={materials.glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.back_up_window_grills001_pure_black_0.geometry}
          material={materials.pure_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.backup_tail_grills001_pure_black_0.geometry}
          material={materials.pure_black}
          position={[0, 0, 32.568]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.backup_vents_carbon_fiber_0.geometry}
          material={materials.carbon_fiber}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.custom_hood_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.custom_hood001_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors001_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors002_carbon_fiber_0.geometry}
          material={materials.carbon_fiber}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors003_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors004_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors005_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors006_pure_black_0.geometry}
          material={materials.pure_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors007_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors008_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors009_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors010_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors011_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors012_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors013_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors014_glass_0.geometry}
          material={materials.glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors016_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors018_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Bumper_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Bumper001_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Bumper002_pure_black_0.geometry}
          material={materials.pure_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Bumper003_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Bumper004_glass_0.geometry}
          material={materials.glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Bumper005_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Bumper006_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Bumper007_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Front_Bumper008_white_lights_0.geometry}
          material={materials.white_lights}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HoneyComb_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Hood003_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_chrome_0.geometry}
          material={materials.chrome}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane004_body_0.geometry}
          material={materials.body}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_chrome_0.geometry}
          material={materials.chrome}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HoneyComb003_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HoneyComb004_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_black_0.geometry}
          material={materials.black}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_white_lights_0.geometry}
          material={materials.white_lights}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_black_0.geometry}
          material={materials.black}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_glass_0.geometry}
          material={materials.glass}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_black_0.geometry}
          material={materials.black}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_black_0.geometry}
          material={materials.black}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_white_lights_0.geometry}
          material={materials.white_lights}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008_black_0.geometry}
          material={materials.black}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009_white_lights_0.geometry}
          material={materials.white_lights}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_black_0.geometry}
          material={materials.black}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_black_0.geometry}
          material={materials.black}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012_black_0.geometry}
          material={materials.black}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_white_lights_0.geometry}
          material={materials.white_lights}
          position={[0, 0, 48.99]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HoneyComb001_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HoneyComb002_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007_glass_0.geometry}
          material={materials.glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane008_chrome_0.geometry}
          material={materials.chrome}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane009_pure_black_0.geometry}
          material={materials.pure_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors015_matte_black_0.geometry}
          material={materials.matte_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors019_matte_black_0.geometry}
          material={materials.matte_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors020_matte_black_0.geometry}
          material={materials.matte_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors021_pure_black_0.geometry}
          material={materials.pure_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane010_pure_black_0.geometry}
          material={materials.pure_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_pure_black_0.geometry}
          material={materials.pure_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.roof_pure_black_0.geometry}
          material={materials.pure_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Doors022_black_0.geometry}
          material={materials.black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_glass_0.geometry}
          material={materials.glass}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle006_pure_black_0.geometry}
          material={materials.pure_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_pure_black_0.geometry}
          material={materials.pure_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_secondary_0.geometry}
          material={materials.secondary}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012_license_plate_0.geometry}
          material={materials.license_plate}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.backup_vents001_pure_black_0.geometry}
          material={materials.pure_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_matte_black_0.geometry}
          material={materials.matte_black}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}
export default Model;

useGLTF.preload('/model/audi.glb')